title: Notes on becoming a person
description: ""
url: https://myaccount.github.io
baseurl: /writing
permalink: /:slug/
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
timezone: Europe/Berlin
